function [matrix] = dh_link(theta,alpha,rx,dz,angle)

if angle == "d"
    matrix = [
        cosd(theta) -sind(theta)*cosd(alpha) sind(theta)*sind(alpha) rx*cosd(theta);...
        sind(theta) cosd(theta)*cosd(alpha) -cosd(theta)*sind(alpha) rx*sind(theta);...
        0 sind(alpha) cosd(alpha) dz;...
        0 0 0 1 ...
    ];
end
if angle == "r"
    matrix = [
        cos(theta)                  -sin(theta)                     0                   rx;...
        sin(theta)*cos(alpha)       cos(theta)*cos(alpha)           -sin(alpha)         -sin(theta)*dz;...
        sin(theta)*sin(alpha)       cos(theta)*sin(alpha)           cos(alpha)          cos(alpha)*dz;...
        0 0 0 1 ...
    ];
end
matrix = vpa(matrix);
end